# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "ML x AI"
description: > # this means to ignore newlines until "email:"
   Notes for my journey in machine learning and artificial intelligence

email: mr.nimit@gmail.com
#blog logo
logo: "/assets/images/logo.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cover-opt.jpg"

name: 'Nimit Pattanasri'
author: 'Nimit Pattanasri'
author_image: "/assets/images/nimit-opt.jpg"

paginate:	5

url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@nimitpattanasri'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/nimitpattanasri
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/nimitpattanasri
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

# Build settings
#markdown: kramdown
#kramdown:
#  math_engine: mathjax
#highlighter: rouge
